[package]
name = "chapter-2"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
luminance = "0.40"
luminance-derive = "0.6"
luminance-glfw = "0.13"
glfw = "0.39"
