[package]
name = "chapter-2"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
glfw = "0.41"
luminance = "0.44"
luminance-derive = "0.7"
luminance-glfw = "0.16"
luminance-windowing = "0.10"
