[package]
name = "chapter-3"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17"
glfw = "0.39"
luminance = "0.40"
luminance-derive = "0.6"
luminance-front = "0.1"
luminance-glfw = "0.13"
try-guard = "0.2"
wavefront_obj = "7"
