[package]
name = "chapter-1"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
luminance = "0.41"
luminance-glfw = "0.13"
luminance-windowing = "0.9"
glfw = "0.39"
