[package]
name = "chapter-1"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
glfw = "0.41"
luminance = "0.43"
luminance-glfw = "0.15"
luminance-windowing = "0.9"
